---
- name: Evaluate {{ operators_project }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: workshop-operators
    namespace: '{{ operators_project }}'

- name: Evaluate Serverless Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'serverless-subscription.yaml.j2') }}"

- name: Wait for Serverless operator to install
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: knativeservings.operator.knative.dev
  register: crd_serving
  until: crd_serving.resources | list | length == 1
  retries: 100
  delay: 30

- name: Create Serverless Serving
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'knative-serving.yaml.j2') }}"
