---
- name: "NA enablement - Day Three Camel K setup"
  hosts: workshop
  become: false
  gather_facts: false
  tags:
    - install
  tasks:
    - name: Check if desired virtualenv is available on the host
      stat:
        path: "/opt/virtualenvs/k8s/bin/python"
      register: r_virtualenv
    - name: Set Ansible Python interpreter to virtualenv
      when: r_virtualenv.stat.exists
      set_fact:
        ansible_python_interpreter: "/opt/virtualenvs/k8s/bin/python"
    - include_role:
        name: camel_projects
      with_sequence: start=1 end={{ num_users }} format=%d
      tags: camel_projects
    - include_role:
        name: provision_camelk
      tags: provision_camelk
    - include_role:
        name: provision_serverless
      vars:
        operators_project: "workshop-operators"
      tags: provision_serverless
    - include_role:
        name: provision_eventing
      vars:
        operators_project: "workshop-operators"
      tags: provision_eventing
    - include_role:
        name: provision_streams
      vars:
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: provision_jaeger
      vars:
        operators_project: "workshop-operators"
      tags: provision_jaeger
    - include_role:
        name: provision_tekton
      vars:
        operators_project: "workshop-operators"
      tags: provision_tekton
    - include_role:
        name: provision_amqbroker
      with_sequence: start=1 end={{ num_users }} format=%d
      tags: provision_amqbroker
    - include_role:
        name: provision_teiid_camel
      with_sequence: start=1 end={{ num_users }} format=%d
      tags: provision_teiid_camel
    - include_role:
        name: provision_prometheus
      with_sequence: start=1 end={{ num_users }} format=%d
      tags: provision_prometheus
    - name: extract route_subdomain
      k8s_facts:
        kind: Ingress
      register: route_subdomain_r
    - name: output workshop info
      debug:
        msg:
        - "user.info: "
        - "user.info: Integration NA Enablement Day Three Camel 2020 - Installed for {{ num_users }} user(s)"
        - "user.info: OpenShift Console: https://console-openshift-console.{{ route_subdomain_r.resources[0].spec.domain | trim }}"
        - "user.info: Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
      when: not silent|bool
