---
- name: Evaluate Camel K Nightly OperatorSource
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camelk-operatorsource.yaml.j2') }}"

- name: Adding edit right to Camel K
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camel-k-edit-admin.yaml.j2') }}"

- name: Evaluate Camel K Subscription in user{{ item }} projects
  include_tasks: user-project.yaml
  with_sequence: start=1 end={{ num_users }} 
  when:
    - num_users|int > 0