---
- name: Evaluate user{{ item }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: user{{ item }}-lab-streaming
    state: present

- name: Evaluate AMQ Broker Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'amqbroker-subscription.yaml.j2') }}"